apiVersion: v1
kind: Secret
metadata:
  name: guacamole-credentials
  namespace: kubebuilderproject-system
type: Opaque
data:
  # Base64 encoded values (guacadmin/guacadmin)
  # echo -n "guacadmin" | base64
  username: Z3VhY2FkbWlu
  password: Z3VhY2FkbWlu
#---
# Example of how to create the secret using kubectl:
# kubectl create secret generic guacamole-credentials \
#   --from-literal=username=guacadmin \
#   --from-literal=password=guacadmin \
#   -n kubebuilderproject-system

