# This rule is not used by the project kubebuilderproject itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubevirt.setofangdar.polito.it.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilderproject
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-admin-role
rules:
- apiGroups:
  - kubevirt.setofangdar.polito.it
  resources:
  - virtualmachines
  verbs:
  - '*'
- apiGroups:
  - kubevirt.setofangdar.polito.it
  resources:
  - virtualmachines/status
  verbs:
  - get
