apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: guacamole
type: Opaque
data:
  POSTGRES_USER: Z3VhY2Ftb2xl
  POSTGRES_PASSWORD: Z3VhY2Ftb2xl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: guacamole
data:
  guacamole.properties: |
    guacd-hostname=guacd
    guacd-port=4822
    postgresql-hostname=postgres
    postgresql-port=5432
    postgresql-database=guacamole_db
    postgresql-username=guacamole
    postgresql-password=guacamole
    openid-allow-unverified-users=true
    openid-username-claim-type=preferred_username
    postgresql-auto-create-accounts=true
    openid-auto-create-groups=true
    openid-groups-claim-type=groups
    openid-groups-claim-name=groups
    openid-authorization-groups-attribute=groups
    openid-authorization-endpoint=http://${NODE_IP}:30081/realms/GuacamoleRealm/protocol/openid-connect/auth
    openid-token-endpoint=http://${NODE_IP}:30081/realms/GuacamoleRealm/protocol/openid-connect/token
    openid-jwks-endpoint=http://${NODE_IP}:30081/realms/GuacamoleRealm/protocol/openid-connect/certs
    openid-issuer=http://${NODE_IP}:30081/realms/GuacamoleRealm
    openid-client-id=guacamole
    openid-redirect-uri=http://${NODE_IP}:30080/guacamole/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-guacamole-realm
  namespace: guacamole
data:
  guacamole-realm.json: |
    {
      "realm": "GuacamoleRealm",
      "enabled": true,
      "clients": [
        {
          "clientId": "guacamole",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "redirectUris": ["http://${NODE_IP}:30080/guacamole/*"],
          "webOrigins": ["http://${NODE_IP}:30080/guacamole/"],
          "rootUrl": "http://${NODE_IP}:30080/guacamole/",
          "baseUrl": "http://${NODE_IP}:30080/guacamole/",
          "standardFlowEnabled": true,
          "implicitFlowEnabled": true,
          "protocolMappers": [
            {
              "name": "preferred_username",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "username",
                "claim.name": "preferred_username",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            },
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "claim.name": "groups",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "groups": [
        {
          "name": "guacusers",
          "path": "/guacusers",
          "attributes": {}
        }
      ],
      "users": [
        {
          "username": "testuser",
          "enabled": true,
          "email": "testuser@test.com",
          "firstName": "Test",
          "lastName": "User",
          "groups": [
            "guacusers"
          ],
          "credentials": [
            {
              "type": "password",
              "value": "testpassword",
              "temporary": false
            }
          ]
        }
      ]
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-db-pvc
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guacamole
spec:
  selector:
    app: guacd
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: guacamole
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  type: NodePort
  selector:
    app: guacamole
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: guacamole
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: guacamole
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:1.5.5
          imagePullPolicy: Always
          ports:
            - containerPort: 4822
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/guacamole
            - name: POSTGRES_DB
              value: guacamole_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: guacamole-db-pvc
        - name: init-scripts
          hostPath:
            path: ${PROJECT_ROOT}/stack/db/init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.5.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
          volumeMounts:
            - name: guacamole-config
              mountPath: /etc/guacamole
            - name: quickconnect-extension
              mountPath: /etc/guacamole/extensions
            - name: jdbc-lib
              mountPath: /etc/guacamole/lib
      volumes:
        - name: guacamole-config
          configMap:
            name: guacamole-config
        - name: quickconnect-extension
          hostPath:
            path: ${PROJECT_ROOT}/stack/guacamole/extensions
        - name: jdbc-lib
          hostPath:
            path: ${PROJECT_ROOT}/stack/guacamole/lib
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: keycloak-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-db-storage
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args:
            - start-dev
            - --hostname-url=http://${NODE_IP}:30081
            - --hostname-strict=false
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-db:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/keycloak/data/import/guacamole-realm.json
              subPath: guacamole-realm.json
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-guacamole-realm
