apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2025-01-02T16:17:18Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: vm2
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm2
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk0
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 2048M
      volumes:
        - name: disk0
          persistentVolumeClaim:
            claimName: ubuntu2
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm2
              password: ubuntu
              sudo: ALL=(ALL) NOPASSWD:ALL
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: false
              ssh_authorized_keys:
              - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNkkw3TPcYkn1kUkDMYK762kUvY2aGdSAo/f7G99TUmgmttKS/POyogkb3ZgJNBMlaSPOa4sizTMvuRggYjKAp9CUcyh6eXjvYEEFitr2fYeAVCjpdmysNr1mmzbn7U6/cWJmphfDRgnxvjRd1zszDuCqQbvJEmD78FFn9VqhgbkuEfjPJojh1RqqSAxLe3Hv+gFN3OQw9UR1x7X75JFKXmO634aaM0N2tExaYGXuf4vCQrwOpBlEFtNRrnlBv/d2J+h0itCE4a8EIPHAUsrSZ4LpgcEEcqKnHW4ScygUGtOCgptnvurtx1CV8WcZUKIdIIt9qhc5+hOOSokAmMf7JkkY2wRvgYbLW/lZZrU6cgAfdzYpIMkfO3EAGxbv3H+ZpAhXd0D7dBsXtaLRvG3kIA3zYDVca/1tzfsWs2gAaeo1v+VJUQNI7ycMzarlrqJii7SrlAuhnjuayUsjlYbw4lTBFhBo0SNpuLidiReww1pJtuV5hp+2vs8hdqghDYLc= aliii@starkindustries
          name: cloudinitdisk
