#!/bin/bash

# Simple script to populate Ansible inventory with VM IPs

INVENTORY_FILE="ansible/inventory"

echo "Populating VM inventory..."

# Get all VM IPs
VM_IPS=$(kubectl get vmi -o jsonpath='{.items[*].status.interfaces[0].ipAddress}' | tr ' ' '\n' | grep -v '^$')

if [ -z "$VM_IPS" ]; then
    echo "No VMs found with IP addresses"
    exit 1
fi

# Create inventory file
cat > "$INVENTORY_FILE" << EOF
# KubeVirt VM Inventory
# Generated by populate-inventory.sh

[vms]
EOF

# Add each VM IP
for ip in $VM_IPS; do
    if [ -n "$ip" ] && [ "$ip" != "<no value>" ]; then
        echo "$ip" >> "$INVENTORY_FILE"
    fi
done

# Add variables
cat >> "$INVENTORY_FILE" << EOF

[vms:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
EOF

echo "Populated inventory with VMs:"
echo "$VM_IPS"
echo ""
echo "Inventory file: $INVENTORY_FILE"
echo ""
echo "Now run: ansible-playbook ansible/configure-vms.yml"
